### ISSUE TITLE
Wrong peculiar velocity 'corrections'.

### ISSUE THREAD

**Issue by rameez3333** [dscolnic/Pantheon#2]
This dataset (Ancillary_G10.FITRES) has significant errors. Many SNe at redshifts far higher than the extent of the flow model used for peculiar velocity corrections (Carrick et al 2015) have high peculiar velocities (VPEC) that cannot be explained by either the 369 km/s CMB rest to heliocentric frame velocity or the 159 km/s Vext of the flow model. An illustrative example is the case of SN 2246 , which has a ZCMB of 0.19422. It seems to have a VPEC of 444.2816. The SNe is  117 degrees away from the CMB dipole, and 115 degrees away from the direction of the Vext.
I find many other SDSS SNe at similar high redshifts to have such high velocities.

This issue was brought to the attention of Dan Scolnic (email communication on Wednesday, 4 July 2018 at 13:18 CEST). I quote his reply verbatim below:

“
Hi Rameez,

Thanks for the question.  I’m also now confused by this - how the peculiar velocity code spits out corrections at high z.  I’ve asked the peculiar velocity people who wrote the code and I’ll let you know when I hear.  There must be some weird extrapolation, but I don’t feel good about it.  It’s a small effect on cosmology, but I’d like to understand what’s going on.
D
“

However, the data seems to not have been fixed so far. 

This issue is particularly alarming in view of the fact that the actually measured heliocentric frame redshifts are not publicly available to the end user easily (like it was for the Joint Lightcurve Analysis catalogue). Scolnic was kind enough to provide a table through personal communication, but it did not correspond to the SNe of Ancillary_G10.FITRES one to one, had -inf values for some and finite precision issues. The table at https://archive.stsci.edu/prepds/ps1cosmo/scolnic_datatable.html has a ZCMB and a ZHEL column, both with exactly the same numbers. This is probably an innocent mistake.

The impact of peculiar velocity ‘corrections’ of this variety on cosmological parameter estimation are nontrivial. Repeating the principled statistical analysis of Nielsen et al 2016 on the JLA catalogue with z_hel instead of z_cmb results in \Omega_M = 0.2849 and \Omega_{\Lambda}= 0.4831 with only ~2.5 sigma evidence for acceleration.  Subtracting out the bias corrections to m_B also results in \Omega_M = 0.2346and \Omega_{\Lambda}= 0.3960 with <2 sigma evidence for acceleration. This is in contradiction to Table 11 of Betoule et al 2014.

In view of this, it is important that the true, un’corrected’ redshifts and magnitudes of the Pantheon compilation be made publicly available, for any credible usage of this dataset for fundamental physics.

**Comment by dscolnic** [comment]
Hi - I have posted a new file that has no peculiar velocity corrections for z>0.08.
