### ISSUE TITLE
Inconsistent redshifts

### ISSUE THREAD

**Issue by rameez3333** [dscolnic/Pantheon#3]
So after the z_hel values were newly submitted following the fix for the peculiar velocity corrections, I took a look for consistency. What I found was so egregious, I wrote it up on arxiv:

https://arxiv.org/abs/1905.00221v1

Dan Scolnic was kind enough to email me quickly, pointing out that SDSS has updated the redshifts, and they're taken from here:

https://classic.sdss.org/supernova/snlist_confirmed.html

According to this URL, for SN15301 (which I presume is the same as SDSS 15301) the redshift is 0.29630. According to JLA it’s 0.248 and according to Pantheon, it is 0.179630.

And in a second email, he pointed me to this URL:

http://skyserver.sdss.org/dr14/en/tools/explore/Summary.aspx?id=1237663458316125530
(the above value agrees more or less with the quoted Pantheon one, for 15301).

So now we have 3 redshifts going around for the same SN, each differing from the other by 100s of Mpcs. Things are getting weird. 

Is it even possible to do cosmology with this dataset? Also, even if SDSS actually 'updated' their redshifts, did it occur to no one to ask why it has changed by more than 130 times the quoted uncertainty (or at least 13 times, if we take the much more conservative value of 0.005)?

If you dont have confidence in your individual SN and their observables, how are you so sure about the statistical significance of acceleration and H0 tension?

I did not mean to imply the existence of any mischief. It appears everyone is just confused here. But the basic question stands, how can cosmology be done with a dataset that's turned out to be so inconsistent in its fundamentals?

**Comment by dscolnic** [comment]
With public lightcurves and redshifts, I encourage scientists to conduct their own analyses.
